services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: restroApp
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data: