# Generated by Django 6.0.6 on 2026-07-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration',
            field=models.CharField(choices=[('email', 'Email')], default=models.EmailField(max_length=254, unique=True)),
        ),
    ]
