# Generated by Django 6.0.6 on 2026-07-05 04:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu/')),
                ('title', models.CharField(max_length=100)),
                ('show_title', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('old_price', models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.CharField(max_length=500)),
                ('tags', models.CharField(help_text='Comma-separated tags', max_length=200)),
                ('chef_tags', models.CharField(blank=True, max_length=30, null=True)),
                ('food_category', models.CharField(blank=True, max_length=30, null=True)),
                ('cook_time', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('calory', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('guest', models.CharField(choices=[('1', '1 Person'), ('2', '2 People'), ('3-4', '3 - 4 People'), ('5-6', '5 - 6 People'), ('7-10', '7 - 10 People'), ('10+', '10+ People')])),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('09:00 AM', '09:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM'), ('02:00 PM', '02:00 PM'), ('06:00 PM', '06:00 PM'), ('07:00 PM', '07:00 PM'), ('08:00 PM', '08:00 PM'), ('09:00 PM', '09:00 PM'), ('10:00 PM', '10:00 PM')])),
                ('special_request', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restroApp.food')),
            ],
            options={
                'unique_together': {('user', 'food')},
            },
        ),
    ]
