# Generated by Django 6.0.6 on 2026-06-21 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0002_alter_food_calory_alter_food_cook_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='user',
        ),
    ]
