# Generated by Django 6.0.6 on 2026-06-21 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0003_remove_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='old_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
