# Generated by Django 6.0.6 on 2026-06-21 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0004_food_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='old_price',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
