# Generated by Django 6.0.6 on 2026-06-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0005_alter_food_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
