# Generated by Django 6.0.6 on 2026-06-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0008_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
