# Generated by Django 6.0.6 on 2026-06-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0010_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
