# Generated by Django 6.0.6 on 2026-06-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restroApp', '0011_alter_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
